---
- name: Cek Datastore ESXi
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Cek datastore
      community.vmware.vmware_datastore_info:
        hostname: "10.10.10.2"
        username: "root"
        password: "@bcd1234"
        validate_certs: false
      delegate_to: localhost
      register: ds

    - name: Tampilkan datastore
      debug:
        msg: "{{ ds }}"