---
- name: Cek ESXi Info
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Cek datastore
      community.vmware.vmware_datastore_info:
        hostname: "10.10.10.2"
        username: "root"
        password: "@bcd1234"
        validate_certs: false
      delegate_to: localhost
      register: ds

    - name: Tampilkan datastore
      debug:
        msg: "{{ ds }}"

    - name: Cek portgroup
      community.vmware.vmware_portgroup_info:
        hostname: "10.10.10.2"
        username: "root"
        password: "@bcd1234"
        validate_certs: false
        esxi_hostname: "10.10.10.2"
      delegate_to: localhost
      register: net

    - name: Tampilkan network
      debug:
        msg: "{{ net }}"