---
- name: Test koneksi ESXi
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Cek info ESXi
      community.vmware.vmware_about_info:
        hostname: "192.168.1.23"
        username: "root"
        password: "@bcd1234"
        validate_certs: false
      delegate_to: localhost
      register: esxi_info

    - name: Tampilkan info ESXi
      debug:
        var: esxi_info
    